# Generated by Django 3.2.7 on 2021-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210926_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='positionX',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='entity',
            name='positionY',
            field=models.IntegerField(default='0'),
        ),
    ]
