# Generated by Django 3.2.7 on 2021-09-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210926_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ermodel',
            name='entities',
        ),
        migrations.AddField(
            model_name='entity',
            name='er_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='backend.ermodel'),
            preserve_default=False,
        ),
    ]
